services:
  db:
    image: postgres:17.6-alpine
    container_name: mtg-quiz-db
    ports:
      - "5001:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:
